import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { architectureOwner, auditArchitectureBoundaries } from '../shared/architecture-boundary-audit.js';
const extensionRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
function collect(directory, output=[]){for(const entry of fs.readdirSync(directory,{withFileTypes:true})){const file=path.join(directory,entry.name);if(entry.isDirectory()){if(!['tests','testing'].includes(entry.name))collect(file,output);}else if(/.js$/.test(entry.name)){const relative=path.relative(extensionRoot,file).replaceAll('\\','/');const source=fs.readFileSync(file,'utf8');const imports=[];for(const match of source.matchAll(/(?:from\s+|import\s*\()(['"])([^'"]+)\1/g)){const specifier=match[2];if(!specifier.startsWith('.'))continue;const target=path.relative(extensionRoot,path.resolve(path.dirname(file),specifier)).replaceAll('\\','/');imports.push(target);}output.push({path:relative,imports,lines:source.split(/\r?\n/).length});}}return output;}
test('architecture owners classify runtime surfaces deterministically',()=>{assert.equal(architectureOwner('background.js'),'background');assert.equal(architectureOwner('content/entry.js'),'content');assert.equal(architectureOwner('dashboard/dashboard.js'),'dashboard');assert.equal(architectureOwner('shared/protocol.js'),'shared');});
test('architecture boundary audit rejects reverse dependencies',()=>{const result=auditArchitectureBoundaries([{path:'shared/a.js',imports:['content/b.js']},{path:'dashboard/a.js',imports:['shared/b.js']}]);assert.equal(result.ok,false);assert.deepEqual(result.violations.map(item=>item.code),['architecture_dependency_reversed']);});
test('production modules preserve one-way ownership boundaries',()=>{const modules=collect(extensionRoot);const result=auditArchitectureBoundaries(modules);assert.equal(result.ok,true,JSON.stringify(result.violations,null,2));});
test('known architecture hotspots remain inside the 0.10.3 growth envelope',()=>{const modules=collect(extensionRoot);const limits={'shared/runtime-pilot-controller.js':2400,'dashboard/dashboard.js':2300,'shared/runtime-pilot-state.js':1600,'content/entry.js':1350};for(const [file,limit] of Object.entries(limits)){const value=modules.find(item=>item.path===file);assert.ok(value,`missing hotspot ${file}`);assert.ok(value.lines<=limit,`${file} grew to ${value.lines} lines above ${limit}`);}});
