import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { deriveOperatorDecisionCenter } from '../shared/operator-decision-center.js';
import { deriveOperatingProfile, operatingProfileEligibility } from '../shared/operating-profile.js';
import { deriveContextualNavigation } from '../shared/cockpit-navigation.js';
import { applyContainmentOverride, deriveContainmentStatus } from '../shared/containment-status.js';
import { deriveTransportAssurance } from '../shared/transport-assurance.js';
import { deriveProviderRouteReadiness } from '../shared/provider-route-readiness.js';
import { deriveUpgradeReadiness } from '../shared/upgrade-readiness.js';
import { deriveLiveScorecard } from '../shared/live-scorecard.js';
import { deriveProductionDiagnostics } from '../shared/production-diagnostics.js';
import { buildHandoffManifest, deriveReleaseHandoff } from '../shared/release-handoff.js';
import { RuntimePilotState } from '../shared/runtime-pilot-state.js';
import { migrateRuntimeEnvelope, registeredRuntimeMigrations } from '../shared/runtime-state-migrations.js';
import { RUNTIME_STATE_SCHEMA_VERSION } from '../shared/runtime-state-schema.js';

const dashboard = await readFile(new URL('../dashboard/dashboard.js', import.meta.url), 'utf8');
const markup = await readFile(new URL('../dashboard/index.html', import.meta.url), 'utf8');
const protocol = await readFile(new URL('../shared/dashboard-protocol.js', import.meta.url), 'utf8');
const commandRegistry = await readFile(new URL('../shared/operator-command-registry.js', import.meta.url), 'utf8');
const controller = await readFile(new URL('../shared/runtime-pilot-controller.js', import.meta.url), 'utf8');
const css = await readFile(new URL('../dashboard/dashboard.css', import.meta.url), 'utf8');
const handoffScript = await readFile(new URL('../../scripts/build-handoff-manifest.mjs', import.meta.url), 'utf8');

function baseSnapshot() { return { sessionId:'s1', mode:'active', sender:{connected:true,phase:'ready',provider:'chatgpt',adapterCapabilities:{complete:true,required:['composerFinder'],missingRequired:[]},transportLane:{lastMode:'direct',score:100,lastRttMs:5,handshakeReady:true}}, receiver:{connected:true,phase:'ready',provider:'chatgpt',adapterCapabilities:{complete:true,required:['submit'],missingRequired:[]},adapterCapabilityProbation:{writeSafe:true,state:'healthy'},transportLane:{lastMode:'direct',score:100,lastRttMs:7,handshakeReady:true}}, selfTest:{ok:true}, contextArmed:true, deliveryPolicy:{active:false}, storagePressure:{level:'normal'}, ledgerCounts:{pending:0,inFlight:0,failed:0,proven:3}, metrics:{deliverySuccessRate:100,answerAvailabilityRate:100,finalsObserved:3,delivered:3}, liveSession:{phase:'debrief',history:[{phase:'setup'},{phase:'active'},{phase:'debrief'}]}, batchState:{}, warnings:[], timeline:[], productionControls:{operatingProfile:'balanced'}, checkpoint:{id:'c1'} }; }

test('Cycles 196-200: Decision Center ranks explicit no-response ahead of warnings without choosing an option', () => { const snapshot=baseSnapshot(); snapshot.batchState.pendingNoResponse={batchId:'b1',createdAt:10}; snapshot.warnings=[{code:'inbox_waiting',severity:'warn',count:2}]; const value=deriveOperatorDecisionCenter(snapshot,20); assert.equal(value.primary.code,'answer_no_response'); assert.equal(value.primary.actionMode,'choose'); assert.equal(value.primary.command,''); assert.deepEqual(value.primary.choices,['wait','retry','continue']); assert.equal(value.items.every(item=>!('text' in item)),true); });
test('Cycles 201-205: profiles preview exact policy changes and block unsafe Fast mode', () => { const snapshot=baseSnapshot(); snapshot.storagePressure={level:'critical'}; assert.equal(operatingProfileEligibility(snapshot,'fast').allowed,false); const safe=deriveOperatingProfile(baseSnapshot(),'safe'); assert.equal(safe.hold,true); assert.equal(safe.receiverPolicy.pauseAfterAnswer,true); });
test('Cycles 206-210: contextual navigation remains internal to the Pilot', () => { const value=deriveContextualNavigation({production:{decisionCenter:{primary:{code:'answer_no_response',title:'Resolve',command:'resolve_no_response',payload:{action:'continue'}}}}}); assert.deepEqual(value.route,{view:'assist',anchor:'choiceWorkspace',reason:'answer_no_response',internalOnly:true}); assert.equal(value.actionMode,'choose'); assert.equal(value.command,''); });
test('Cycles 211-215: containment override is bounded and cannot bypass hard causes', () => { const snapshot=baseSnapshot(); snapshot.deliveryPolicy={active:true,reason:'provider_unhealthy',allowProviderWrite:false}; snapshot.productionControls={containmentOverrideUntil:200}; assert.equal(applyContainmentOverride(snapshot.deliveryPolicy,snapshot,100).active,false); snapshot.deliveryPolicy.reason='session_storage_critical'; assert.equal(deriveContainmentStatus(snapshot,100).overrideEligible,false); });
test('Cycles 216-220: transport assurance combines both lanes and correlation gaps', () => { const snapshot=baseSnapshot(); snapshot.timeline=[{type:'trace_gap'}]; const value=deriveTransportAssurance(snapshot,100); assert.equal(value.state,'direct'); assert.equal(value.correlationGaps,1); assert.equal(value.score,95); });
test('Cycles 221-225: route readiness requires capabilities context and provider writes', () => { const ready=deriveProviderRouteReadiness(baseSnapshot()); assert.equal(ready.ready,true); const blocked=baseSnapshot(); blocked.contextArmed=false; assert.equal(deriveProviderRouteReadiness(blocked).recommendedCommand,'resend_context'); });
test('Cycles 226-230: upgrade gate waits for unresolved ownership and requires rollback', () => { const snapshot=baseSnapshot(); snapshot.ledgerCounts.pending=2; const value=deriveUpgradeReadiness(snapshot); assert.equal(value.state,'wait'); assert.ok(value.blockers.includes('unresolved_delivery')); });
test('Cycles 231-235: live scorecard separates delivery and answer evidence', () => { const snapshot=baseSnapshot(); snapshot.operatorMarkers=[{category:'strong_answer'},{category:'metric_gap'}]; const value=deriveLiveScorecard(snapshot); assert.equal(value.markerTotal,2); assert.equal(value.deliverySuccessRate,100); assert.equal(value.answerAvailabilityRate,100); });
test('Cycles 236-240: production diagnostics are bounded and content free', () => { const snapshot=baseSnapshot(); const production={decisionCenter:{count:0},operatingProfile:{id:'balanced'},containment:{},transportAssurance:{state:'direct'},routeReadiness:{ready:true},upgradeReadiness:{state:'ready'},scorecard:{}}; const value=deriveProductionDiagnostics(snapshot,production); assert.equal(value.privacy.safe,true); assert.equal(JSON.stringify(value).includes('question text'),false); });
test('Cycles 241-245: handoff requires fresh automated browser cleanup and no-push evidence', () => { const snapshot=baseSnapshot(); const production={diagnostics:{state:'healthy',score:100,privacy:{safe:true},fingerprint:{version:'0.10.0',commit:'abc'}},routeReadiness:{route:'chatgpt -> chatgpt'},operatingProfile:{id:'balanced'}}; const evidence={commit:'abc',expectedCommit:'abc',generatedAt:1,sourceClean:true,automatedOk:true,browserOk:true,assistUiOk:true,cleanupOk:true,noPushMergeTag:true}; const release=deriveReleaseHandoff(snapshot,production,evidence); assert.equal(release.ready,true); const manifest=buildHandoffManifest({snapshot,production,evidence,files:['b','a','a']}); assert.deepEqual(manifest.cleanupFiles,['a','b']); });

test('production controls persist profile override and internal route in session state', () => { const pilot=new RuntimePilotState(); pilot.setOperatingProfile('s1','safe',10,'test'); pilot.setContainmentOverride('s1',true,60000,'test',20); pilot.setProductionNavigation('s1',{view:'production',anchor:'transportAssuranceState',reason:'test'},30); const restored=new RuntimePilotState(pilot.exportState()).snapshot('s1',40); assert.equal(restored.productionControls.operatingProfile,'safe'); assert.equal(restored.productionControls.containmentOverrideUntil,60020); assert.equal(restored.productionControls.lastNavigation.view,'production'); });
test('current migration adds production controls Navigator and turn coordination without losing sessions', () => { assert.equal(RUNTIME_STATE_SCHEMA_VERSION,5); assert.deepEqual(registeredRuntimeMigrations(),['1->2','2->3','3->4','4->5']); const result=migrateRuntimeEnvelope({schemaVersion:2,writerVersion:'0.8.0',committedAt:1,sessions:[{sessionId:'s1'}]},RUNTIME_STATE_SCHEMA_VERSION,{writerVersion:'0.12.0',now:2}); assert.equal(result.envelope.schemaVersion,RUNTIME_STATE_SCHEMA_VERSION); assert.equal(result.envelope.sessions[0].productionControls.operatingProfile,'balanced'); assert.equal(result.envelope.sessions[0].sessionNavigator.defaultTab,'now'); assert.equal(result.envelope.sessions[0].batchState.turnCoordination.mode,'live'); });
test('registry and controller expose only allow-listed production commands', () => { for(const command of ['apply_operating_profile','set_containment_override','probe_transport','record_production_navigation']) { assert.match(commandRegistry,new RegExp(`'${command}'`)); assert.match(controller,new RegExp(`case '${command}'`)); } assert.match(protocol,/registeredCommandIds/); });
test('Production Pilot view exposes every production-readiness surface', () => { for(const id of ['panelProduction','productionDecisionTitle','operatingProfileSelect','containmentState','transportAssuranceState','routeReadinessState','upgradeReadinessState','liveScoreValue','productionDiagnosticsState','releaseHandoffState']) assert.match(markup,new RegExp(`id="${id}"`)); assert.match(dashboard,/function renderProduction/); assert.match(css,/\.production-grid/); });
test('handoff generator binds evidence to clean branch and original checkout', () => { assert.match(handoffScript,/Release evidence commit does not match HEAD/); assert.match(handoffScript,/Tracked working tree is not clean/); assert.match(handoffScript,/originalCheckoutClean/); assert.match(handoffScript,/noPushMergeTagConfirmed/); });
