import test from 'node:test';
import assert from 'node:assert/strict';
import { RequestCorrelationJournal } from '../shared/request-correlation-journal.js';
import { buildSnapshotDelta, applySnapshotDeltaChecked } from '../shared/snapshot-delta.js';
import { createCoalescedCommitLane } from '../shared/persistence-urgency-policy.js';
import { acquireAttemptLease, releaseAttemptLease } from '../shared/delivery-attempt-lease.js';
import { canonicalRenderedTurnIdentity } from '../shared/rendered-turn-identity.js';
import { buildRenderedProofIndex } from '../shared/proof-reconciliation-index.js';
import { buildPartialProofReport, mergePartialProofReports } from '../shared/partial-proof-report.js';
import { deriveProofRetryPolicy } from '../shared/proof-retry-policy.js';
import { evaluateAdapterCapabilityDrift } from '../content/adapter-capability-drift.js';
import { deriveSelfTestTrust } from '../dashboard/self-test-trust-model.js';
import { TransportCircuit } from '../shared/transport-circuit.js';
import { ReconnectPolicy } from '../shared/reconnect-policy.js';
import { prepareSessionEnd, sessionEndCounts } from '../shared/session-end-guard.js';
import { recordUndo, consumeUndo } from '../shared/operator-undo-journal.js';
import { createLiveAnnouncer } from '../dashboard/live-announcer.js';

// Cycles 71-75: correlation and snapshot ordering.
test('Cycle 71: completed request IDs may be reused only in a newer epoch',()=>{const journal=new RequestCorrelationJournal();assert.equal(journal.begin('r',{epoch:1,now:1}).accepted,true);journal.complete('r',{ok:true},2);assert.equal(journal.begin('r',{epoch:1,now:3}).accepted,false);const reused=journal.begin('r',{epoch:2,now:3});assert.equal(reused.accepted,true);assert.equal(reused.replacedEpoch,1);});
test('Cycle 72: bounded journal rejects new work when every retained entry is pending',()=>{const journal=new RequestCorrelationJournal({maxEntries:2});journal.begin('a',{epoch:1});journal.begin('b',{epoch:1});const result=journal.begin('c',{epoch:1});assert.equal(result.accepted,false);assert.equal(result.reason,'request_capacity_exhausted');});
test('Cycle 73: response acceptance atomically claims one settlement owner',()=>{const journal=new RequestCorrelationJournal();journal.begin('r',{epoch:1});assert.equal(journal.acceptResponse('r',1).accepted,true);const duplicate=journal.acceptResponse('r',1);assert.equal(duplicate.accepted,false);assert.equal(duplicate.reason,'duplicate_response');assert.equal(journal.complete('r',{ok:true}),true);});
test('Cycle 74: snapshot delta carries base and next fingerprints with monotonic generation',()=>{const delta=buildSnapshotDelta({a:1},{a:2},{baseGeneration:4,nextGeneration:5});assert.equal(delta.baseGeneration,4);assert.equal(delta.nextGeneration,5);assert.ok(delta.baseFingerprint);assert.ok(delta.nextFingerprint);});
test('Cycle 75: checked snapshot application rejects stale base and out-of-order generation',()=>{const delta=buildSnapshotDelta({a:1},{a:2},{baseGeneration:4,nextGeneration:5});assert.equal(applySnapshotDeltaChecked({a:0},delta,{generation:4}).error,'snapshot_base_mismatch');assert.equal(applySnapshotDeltaChecked({a:1},delta,{generation:3}).error,'snapshot_generation_mismatch');assert.deepEqual(applySnapshotDeltaChecked({a:1},delta,{generation:4}).snapshot,{a:2});});
// Cycles 76-82: persistence, leases, and proof ownership.
test('Cycle 76: reasons scheduled during an in-flight commit are flushed in a follow-up generation',async()=>{const calls=[];let release;const lane=createCoalescedCommitLane({commit:async(session,reasons)=>{calls.push([session,[...reasons]]);if(calls.length===1)await new Promise(resolve=>{release=resolve;});},setTimer:()=>1,clearTimer:()=>{}});lane.schedule('s','first');const flushing=lane.flush('s');await Promise.resolve();lane.schedule('s','second');release();await flushing;assert.deepEqual(calls,[['s',['first']],['s',['second']]]);});
test('Cycle 77: flushAll orders sessions and isolates individual commit failures',async()=>{const lane=createCoalescedCommitLane({commit:async session=>{if(session==='b')throw new Error('failed');},setTimer:()=>1,clearTimer:()=>{}});lane.schedule('b','x');lane.schedule('a','y');const result=await lane.flushAll();assert.deepEqual(result.map(item=>item.sessionId),['a','b']);assert.equal(result[0].ok,true);assert.equal(result[1].ok,false);});
test('Cycle 78: delivery lease takeover rejects ABA and stale release',()=>{const first=acquireAttemptLease(null,{owner:'a',now:1,ttlMs:5,leaseId:'l1'}).lease;const stale=acquireAttemptLease(first,{owner:'b',now:10,expectedLeaseId:'other',leaseId:'l2'});assert.equal(stale.accepted,false);assert.equal(stale.reason,'attempt_lease_expected_mismatch');const second=acquireAttemptLease(first,{owner:'b',now:10,expectedLeaseId:'l1',leaseId:'l2'}).lease;assert.equal(second.generation,2);assert.equal(releaseAttemptLease(second,{leaseId:'l1',generation:1}).released,false);});
test('Cycle 79: rendered identity distinguishes repeated text by conversation and stable neighbors',()=>{const base={provider:'p',role:'user',text:'same',ordinal:1};const a=canonicalRenderedTurnIdentity({...base,conversationId:'c1',previousStableId:'p1',nextStableId:'n1'});const b=canonicalRenderedTurnIdentity({...base,conversationId:'c2',previousStableId:'p2',nextStableId:'n2'});assert.notEqual(a.identity,b.identity);});
test('Cycle 80: one rendered proof record cannot prove two batches after consumption',()=>{const prompt={questionCount:1,text:'question one'};const index=buildRenderedProofIndex([{id:'u1',role:'user',text:'question one'}]);const first=index.match(prompt);assert.equal(first.matched,true);assert.equal(index.consume(first.recordId).consumed,true);assert.equal(index.match(prompt).matched,false);});
test('Cycle 81: later proof removes a member from the mismatched set',()=>{const previous=buildPartialProofReport({batchId:'b',expectedIds:['1'],mismatchedIds:['1'],now:1});const current=buildPartialProofReport({batchId:'b',expectedIds:['1'],provenIds:['1'],now:2});const merged=mergePartialProofReports(previous,current);assert.deepEqual(merged.provenIds,['1']);assert.deepEqual(merged.mismatchedIds,[]);assert.equal(merged.complete,true);});
test('Cycle 82: proof retry delay is deterministic bounded and resets when reason changes',()=>{const a=deriveProofRetryPolicy({batchId:'b',attempt:2,reason:'partial',now:100,randomSeed:'seed'});const b=deriveProofRetryPolicy({batchId:'b',attempt:2,reason:'partial',now:100,randomSeed:'seed'});assert.equal(a.delayMs,b.delayMs);assert.ok(a.delayMs<=5000);const changed=deriveProofRetryPolicy({batchId:'b',attempt:3,reason:'render_changed',previousReason:'partial',now:100,randomSeed:'seed'});assert.equal(changed.attempt,1);});
import { createRuntimePortHub, rolePortName } from '../shared/runtime-port-hub.js';

function event(){const listeners=[];return{addListener(fn){listeners.push(fn);},emit(value){for(const fn of listeners)fn(value);}};}
function fakePort(name){return{name,sender:{tab:{id:1,windowId:2}},onMessage:event(),onDisconnect:event(),sent:[],postMessage(message){this.sent.push(message);}};}
async function handshake(port){const offer=port.sent.find(message=>message.type==='transport_handshake_offer');port.onMessage.emit({type:'transport_handshake_accept',handshake:offer.handshake});await Promise.resolve();await Promise.resolve();const result=port.sent.find(message=>message.type==='transport_handshake_result');port.sent.length=0;return result.protocol;}

// Cycles 83-90: capability, transport, session, undo, and accessibility.
test('Cycle 83: capability drift detects required capabilities omitted from the current report',()=>{const previous={required:['composer','submit'],composer:true,submit:true};const current={required:['composer'],composer:true};const drift=evaluateAdapterCapabilityDrift(previous,current,null,10);assert.deepEqual(drift.criticalRemoved,['submit']);assert.equal(drift.state,'critical');});
test('Cycle 84: future-dated role evidence cannot extend self-test trust',()=>{const now=1000;const role={connected:true,phase:'ready',composerReady:true,heartbeatAt:5000,transportLane:{lastMode:'direct',updatedAt:5000}};const trust=deriveSelfTestTrust({selfTest:{ok:true,completedAt:900},dashboardConnections:1,sender:role,receiver:role},now,{activeMs:10,futureToleranceMs:100});assert.equal(trust.state,'stale');});
test('Cycle 85: only one half-open circuit probe token can own recovery',()=>{let now=100;const circuit=new TransportCircuit({state:'open',nextProbeAt:50},{now:()=>now});const first=circuit.claimProbe(now);assert.equal(first.accepted,true);const second=circuit.claimProbe(now);assert.equal(second.accepted,false);assert.equal(second.reason,'probe_already_owned');assert.equal(circuit.recordSuccess(5,110,{probeId:'wrong'}).state,'probing');assert.equal(circuit.recordSuccess(5,110,{probeId:first.probeId}).state,'closed');});
test('Cycle 86: duplicate inbound request still pending receives bounded retry guidance',async()=>{let finish;const hub=createRuntimePortHub({onFrame:()=>new Promise(resolve=>{finish=resolve;})});const port=fakePort(rolePortName('s','sender','i'));hub.connect(port);const protocol=await handshake(port);const frame={type:'request',requestId:'r',operation:'final',payload:{},protocol};port.onMessage.emit(frame);port.onMessage.emit(frame);await Promise.resolve();const pending=port.sent.find(message=>message.type==='response'&&message.result?.error==='request_pending');assert.equal(pending.result.retryable,true);assert.ok(pending.result.retryAfterMs>0);finish({ok:true});});
test('Cycle 87: reconnect jitter never exceeds configured cap',()=>{const policy=new ReconnectPolicy({baseMs:100,capMs:200,jitter:.5,random:()=>1});policy.next();policy.next();const capped=policy.next();assert.equal(capped.delayMs,200);assert.equal(capped.capped,true);});
test('Cycle 88: session end uses ledger-count fallback and pending command activity',()=>{const counts=sessionEndCounts({ledgerCounts:{unresolved:3},dashboardOperations:{pending:2},liveSession:{phase:'debrief'}});assert.equal(counts.actionable,3);assert.equal(counts.pendingCommands,2);const prepared=prepareSessionEnd({ledgerCounts:{unresolved:3},dashboardOperations:{pending:2},liveSession:{phase:'debrief'}},{now:1});assert.equal(prepared.canEnd,false);});
test('Cycle 89: undo rejects current metadata that no longer matches the recorded after-state',()=>{const journal=recordUndo([],{itemId:'q1',action:'pin',before:{pinned:false},after:{pinned:true}},1);const stale=consumeUndo(journal,journal[0].id,2,{current:{pinned:false}});assert.equal(stale.ok,false);assert.equal(stale.error,'undo_state_changed');const valid=consumeUndo(journal,journal[0].id,2,{current:{pinned:true}});assert.equal(valid.ok,true);});
test('Cycle 90: polite and assertive announcements do not suppress each other and stale microtasks are cancelled',async()=>{const queued=[];const polite={textContent:''},assertive={textContent:''};const announcer=createLiveAnnouncer({politeNode:polite,assertiveNode:assertive,now:()=>100,queueTask:fn=>queued.push(fn)});assert.equal(announcer.announce('same',{priority:'polite'}),true);assert.equal(announcer.announce('same',{priority:'assertive'}),true);announcer.announce('new',{priority:'polite',force:true});queued[0]();queued[2]();queued[1]();assert.equal(polite.textContent,'new');assert.equal(assertive.textContent,'same');});