import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { auditCommandReachability } from '../shared/command-reachability-audit.js';
import { COMMAND_REGISTRY } from '../shared/operator-command-registry.js';
import { normalizeDashboardCommand } from '../shared/dashboard-protocol.js';
import { validateOperatorChoice } from '../shared/operator-choice-model.js';
import { buildPolicyImpactPreview, validatePolicyImpactConfirmation } from '../shared/policy-impact-preview.js';
import { prepareSessionEnd, validateSessionEnd } from '../shared/session-end-guard.js';
import { claimRuntimeInjection } from '../shared/runtime-injection-fence.js';
import { derivePrerenderGuard } from '../shared/prerender-guard.js';
import { auditAndRehydrateAlarms } from '../shared/alarm-rehydration.js';
import { beginCleanupTransaction, recordCleanupStep } from '../shared/cleanup-transaction-journal.js';
import { createSenderOutbox } from '../content/sender-outbox.js';
import { DeliveryLedgerIndex } from '../shared/delivery-ledger-index.js';
import { ContiguousSequenceBuffer } from '../shared/contiguous-sequence-buffer.js';
import { ReceiverCreditHysteresis } from '../shared/receiver-credit-hysteresis.js';
import { scheduleFairBatch } from '../shared/fair-batch-scheduler.js';
import { postAnswerDecision } from '../shared/receiver-delivery-policy.js';
import { buildInterruptPlan } from '../shared/answer-operations.js';
import { createComposerArbiter } from '../content/composer-arbiter.js';
import { deriveProviderRouteReadiness } from '../shared/provider-route-readiness.js';
import { deriveProviderRouteTransition } from '../shared/provider-route-transition.js';
import { utf8Bytes, buildCompactionPlan } from '../shared/storage-accounting.js';
import { buildSnapshotDelta, applySnapshotDelta } from '../shared/snapshot-delta.js';
import { createRenderScheduler } from '../dashboard/render-scheduler.js';
import { virtualItems } from '../dashboard/virtual-list-model.js';
import { deriveBacklogForecast } from '../shared/backlog-forecast.js';
import { normalizeMonotonicClock, monotonicElapsed } from '../shared/monotonic-session-clock.js';
import { auditDashboardAccessibility } from '../dashboard/accessibility-audit.js';
import { applyAccessibilityPreferences } from '../dashboard/accessibility-preferences.js';
import { buildSafeSupportBundle } from '../shared/support-bundle.js';
import { deriveReleaseHandoff } from '../shared/release-handoff.js';
import { deriveLiveActionDock } from '../dashboard/live-action-dock-model.js';
import { deriveCommandHistory } from '../dashboard/command-history-model.js';
import { deriveInboxTriageBoard } from '../dashboard/inbox-triage-board-model.js';
const here=path.dirname(fileURLToPath(import.meta.url));
const dashboardRoot=path.resolve(here,'../dashboard');
const read=name=>fs.readFileSync(path.join(dashboardRoot,name),'utf8');
const command=(id,payload={})=>normalizeDashboardCommand({sessionId:'s',requestId:`r-${id}`,command:id,payload});
const role={provider:'chatgpt',connected:true,phase:'ready',composerReady:true,adapterCapabilities:{complete:true,missingRequired:[]},adapterCapabilityProbation:{writeSafe:true}};

// Cycles 1–6: control-plane and decision integrity.
test('Bug 1: every visible command has one registry and controller owner',()=>{const result=auditCommandReachability({registry:COMMAND_REGISTRY,html:read('index.html'),dashboardSource:read('dashboard.js'),controllerSource:fs.readFileSync(path.resolve(here,'../shared/runtime-pilot-controller.js'),'utf8')});assert.equal(result.ok,true);});
test('Bug 2: dashboard IDs and aria targets are unique and reachable',()=>{const result=auditCommandReachability({registry:COMMAND_REGISTRY,html:read('index.html'),dashboardSource:read('dashboard.js'),controllerSource:fs.readFileSync(path.resolve(here,'../shared/runtime-pilot-controller.js'),'utf8')});assert.deepEqual(result.duplicateDomIds,[]);assert.deepEqual(result.missingAriaTargets,[]);});
test('Bug 3: high-risk payloads discard unknown fields',()=>{const value=command('end_session',{confirmToken:'t',mode:'clean',questionText:'secret',extra:'x'});assert.deepEqual(Object.keys(value.payload).sort(),['confirmToken','mode']);});
test('Bug 4: explicit choices reject stale fingerprints',()=>{const snapshot={batchState:{pendingNoResponse:{batchId:'b',createdAt:1},next:{batchId:'n',memberFingerprint:'f'}}};const current=validateOperatorChoice(snapshot,{choiceId:'choice:no_response:b',fingerprint:'stale',option:'continue'},2);assert.equal(current.ok,false);assert.equal(current.error,'choice_stale');});
test('Bug 5: policy confirmation expires and detects snapshot changes',()=>{const snapshot={sessionId:'s',ledgerCounts:{unresolved:1},productionControls:{operatingProfile:'balanced'}};const preview=buildPolicyImpactPreview(snapshot,{kind:'operating_profile',profile:'safe'},10);assert.equal(validatePolicyImpactConfirmation(snapshot,preview,preview.expiresAt+1).error,'policy_preview_expired');assert.equal(validatePolicyImpactConfirmation({...snapshot,ledgerCounts:{unresolved:2}},preview,20).error,'policy_preview_stale');});
test('Bug 6: Action Dock never exposes an executable action after session end',()=>{const dock=deriveLiveActionDock({mode:'ended',ledgerCounts:{unresolved:2},production:{decisionCenter:{primary:{title:'Run',command:'repair_runtime'}}}});assert.equal(dock.ended,true);assert.equal(dock.action.mode,'inspect');});

// Cycles 7–12: runtime lifecycle and ownership.
test('Bug 7: stale runtime takeover requires lease expiry and non-regressing generation',()=>{const owner=claimRuntimeInjection(null,{instanceId:'a',documentId:'d',generation:2},10,{leaseMs:100});assert.equal(claimRuntimeInjection(owner.owner,{instanceId:'b',documentId:'d2',generation:1},1200,{leaseMs:100}).accepted,false);assert.equal(claimRuntimeInjection(owner.owner,{instanceId:'b',documentId:'d2',generation:2},1200,{leaseMs:100}).accepted,true);});
test('Bug 8: frozen, discarded, and prerendered pages cannot write',()=>{for(const context of [{frozen:true},{discarded:true},{prerendering:true},{lifecycle:'frozen'}])assert.equal(derivePrerenderGuard(context).allowProviderWrite,false);});
test('Bug 9: healthy duplicate runtime is rejected',()=>{const owner=claimRuntimeInjection(null,{instanceId:'a',documentId:'d',generation:1},10);const duplicate=claimRuntimeInjection(owner.owner,{instanceId:'b',documentId:'d2',generation:1},20);assert.equal(duplicate.accepted,false);assert.equal(duplicate.reason,'runtime_owner_healthy');});
test('Bug 10: policy preview becomes unusable after dashboard state changes',()=>{const snapshot={sessionId:'s',productionControls:{operatingProfile:'balanced'}};const preview=buildPolicyImpactPreview(snapshot,{kind:'operating_profile',profile:'safe'},1);assert.equal(validatePolicyImpactConfirmation({...snapshot,deliveryPolicy:{active:true}},preview,2).ok,false);});
test('Bug 11: duplicate alarm schedules are collapsed deterministically',async()=>{const calls=[];const result=await auditAndRehydrateAlarms({schedules:[{alarmName:'pmia-recovery:s',dueAt:50},{alarmName:'pmia-recovery:s',dueAt:70}],now:10,create:async(name,data)=>calls.push([name,data.when])});assert.equal(result.expected,1);assert.equal(calls.length,1);});
test('Bug 12: cleanup cannot skip an unfinished step',()=>{const tx=beginCleanupTransaction({sessionId:'s',now:1});const result=recordCleanupStep(tx,'clear_registry',{ok:true},2);assert.equal(result.ok,false);assert.equal(result.error,'cleanup_step_out_of_order');});
// Cycles 13–18: lossless transport and receiver mechanics.
test('Bug 13: outbox attempt persistence failure prevents delivery send',async()=>{let saves=0,sends=0;const outbox=createSenderOutbox({initialEntries:[{envelope:{id:'e1',sessionId:'s',seq:1}}],saveState:async()=>{saves+=1;if(saves===1)throw new Error('write failed');},now:()=>100,random:()=>0});const result=await outbox.replay(async()=>{sends+=1;return {persisted:true};});assert.equal(sends,0);assert.equal(result[0].response.error,'outbox_attempt_persist_failed');});
test('Bug 14: ledger index repair removes duplicate identity and sequence drift',()=>{const entries=[{id:'a',state:'persisted',envelope:{sourceProvider:'p',seq:1}},{id:'a',state:'failed',envelope:{sourceProvider:'p',seq:2}},{id:'b',state:'persisted',envelope:{sourceProvider:'p',seq:1}}];const index=new DeliveryLedgerIndex(entries);const repaired=index.repair(entries);assert.equal(repaired.entries.length,1);assert.equal(repaired.audit.ok,true);});
test('Bug 15: sequence rejection preserves exact expected sequence',()=>{const buffer=new ContiguousSequenceBuffer({lastAcceptedSeq:1},{maxBuffered:1});assert.equal(buffer.offer({id:'e3',seq:3}).accepted,true);const rejected=buffer.offer({id:'e4',seq:4});assert.equal(rejected.accepted,false);assert.equal(rejected.expectedSeq,2);assert.equal(buffer.nack('gap').expectedSeq,2);});
test('Bug 16: receiver credits cannot exceed capacity and reopen only after stability',()=>{const credits=new ReceiverCreditHysteresis({recoveryWindowMs:100});assert.equal(credits.update({available:5,capacity:2},{now:0}).available,2);credits.update({available:0,capacity:2},{now:10});assert.equal(credits.update({available:2,capacity:2},{now:50}).canAccept,false);assert.equal(credits.update({available:2,capacity:2},{now:150}).canAccept,true);});
test('Bug 17: starved fair partition is promoted without sequence mutation',()=>{const result=scheduleFairBatch([{id:'new',source:'a',oldestAt:900,firstSeq:2},{id:'old',source:'b',oldestAt:1,firstSeq:1}],{now:1201,starvationMs:500});assert.equal(result.selected.id,'old');assert.equal(result.reason,'starvation_promoted');});
test('Bug 18: post-answer no-response requires explicit resolution',()=>{assert.equal(postAnswerDecision({submitOnIdle:true},{nextCount:2,answerState:'no_response'}).action,'await_resolution');});
// Cycles 19–24: provider, storage, and performance.
test('Bug 19: route readiness blocks missing composer and stale self-test',()=>{const result=deriveProviderRouteReadiness({sender:role,receiver:{...role,composerReady:false},contextArmed:true,selfTest:{ok:false}});assert.equal(result.ready,false);assert.ok(result.blockers.includes('receiver_composer_not_ready'));assert.ok(result.blockers.includes('self_test_not_ready'));});
test('Bug 20: provider route transition freezes writes while protected batches exist',()=>{const result=deriveProviderRouteTransition({previous:{route:'a -> b',ready:true},current:{route:'a -> c',ready:true},activeCount:1,nextCount:2});assert.equal(result.freezeWrites,true);assert.equal(result.protectedCount,3);});
test('Bug 21: storage compaction never proposes actionable bytes',()=>{const plan=buildCompactionPlan({total:100,actionable:70,telemetry:10,snapshots:10,proven:10},20);assert.equal(plan.actionableProtected,true);assert.equal(plan.plan.some(step=>step.category==='actionable'),false);});
test('Bug 22: snapshot delta round trip preserves changed and removed sections',()=>{const delta=buildSnapshotDelta({a:1,b:2},{a:3,c:4});assert.deepEqual(applySnapshotDelta({a:1,b:2},delta),{a:3,c:4});});
test('Bug 23: virtual list remains bounded with invalid dimensions',()=>{const result=virtualItems(Array.from({length:100},(_,i)=>i),{scrollTop:Infinity,viewportHeight:NaN,rowHeight:0,overscan:5});assert.ok(result.start>=0);assert.ok(result.end<=100);assert.ok(result.items.length<=100);});
test('Bug 24: backlog forecast does not report a breach from insufficient throughput evidence',()=>{const result=deriveBacklogForecast({queued:4,oldestAgeMs:5000,targetMs:20000,proofLatenciesMs:[],proofs:[]});assert.notEqual(result.risk,'breached');assert.equal(result.proofsPerMinute,0);});
// Cycles 25–30: accessibility, privacy, browser evidence, and handoff.
test('Bug 25: accessibility audit reports duplicate IDs and missing controlled targets',()=>{const html='<button id="a" aria-controls="missing">A</button><div id="a"></div><div aria-live="polite"></div><div aria-live="assertive"></div>';const result=auditCommandReachability({registry:[],html,dashboardSource:'',controllerSource:''});assert.deepEqual(result.duplicateDomIds,['a']);assert.deepEqual(result.missingAriaTargets,['missing']);});
test('Bug 26: accessibility preferences tolerate absent roots and media-query failures',()=>{const result=applyAccessibilityPreferences(null,{reducedMotion:'system'},()=>{throw new Error('unavailable');});assert.equal(result.applied,false);assert.equal(result.effectiveReducedMotion,false);});
test('Bug 27: support bundle recursively excludes sensitive interview content',()=>{const bundle=buildSafeSupportBundle({sessionId:'s',ledger:[{id:'e',state:'proven',envelope:{seq:1,metadata:{questionText:'secret',traceId:'t'}}}],performanceBudget:{nested:{clipboard:'secret',durationMs:3}},production:{diagnostics:{privacy:{safe:true}}}},{manifest:{name:'PMIA',version:'0.10.0'}});const raw=JSON.stringify(bundle);assert.equal(raw.includes('secret'),false);assert.equal(bundle.privacy.safe,true);});
test('Bug 28: dashboard markup retains unique required controls',()=>{const result=auditCommandReachability({registry:COMMAND_REGISTRY,html:read('index.html'),dashboardSource:read('dashboard.js'),controllerSource:fs.readFileSync(path.resolve(here,'../shared/runtime-pilot-controller.js'),'utf8')});assert.equal(result.ok,true);assert.equal(read('index.html').includes('assistReliabilityGroups'),true);});
test('Bug 29: isolated smoke requires Assist and Production evidence',()=>{const smoke=fs.readFileSync(path.resolve(here,'../../scripts/isolated-release-smoke.mjs'),'utf8');assert.match(smoke,/assistUiOk/);assert.match(smoke,/productionUiOk/);assert.match(smoke,/commandReachability/);});
test('Bug 30: release handoff fails closed without exact clean evidence',()=>{const production={diagnostics:{state:'healthy',score:100,privacy:{safe:true},fingerprint:{version:'0.10.0',commit:'abc'}}};const result=deriveReleaseHandoff({ledgerCounts:{unresolved:0}},production,{commit:'abc',automatedOk:true,browserOk:true,assistUiOk:true,cleanupOk:true,noPushMergeTag:true});assert.equal(result.ready,false);assert.ok(result.failed.includes('source'));});

// Additional bug cycles 31–40.
test('Bug 31: Action Dock counts unique unresolved ownership once',()=>{const dock=deriveLiveActionDock({ledgerCounts:{unresolved:3,pending:3,inFlight:2}});assert.equal(dock.waiting,3);});
test('Bug 32: route readiness requires a fresh successful self-test when evidence exists',()=>{const result=deriveProviderRouteReadiness({sender:role,receiver:role,contextArmed:true,selfTest:{ok:false}});assert.ok(result.blockers.includes('self_test_not_ready'));});
test('Bug 33: support-export command strips every supplied field',()=>{assert.deepEqual(command('export_support_bundle',{question:'x',url:'https://x',extra:1}).payload,{});});
test('Bug 34: preview confirmation is one snapshot contract rather than a free-form profile request',()=>{const snapshot={sessionId:'s',productionControls:{operatingProfile:'balanced'}};const preview=buildPolicyImpactPreview(snapshot,{kind:'operating_profile',profile:'safe'},10);const normalized=command('apply_operating_profile',{profile:'safe',preview,extra:'drop'});assert.deepEqual(Object.keys(normalized.payload).sort(),['preview','profile']);});
test('Bug 35: end-session confirmation rejects authoritative count changes',()=>{const prepared=prepareSessionEnd({ledgerCounts:{unresolved:0},liveSession:{phase:'debrief'}},{now:1});const result=validateSessionEnd(prepared,{token:prepared.token,mode:'clean',now:2,currentCounts:{...prepared.counts,actionable:1}});assert.equal(result.error,'session_end_state_changed');});
test('Bug 36: failed cleanup step must be retried before later work',()=>{let tx=beginCleanupTransaction({sessionId:'s',now:1});tx=recordCleanupStep(tx,'freeze_commands',{ok:false,error:'x'},2).transaction;assert.equal(recordCleanupStep(tx,'export_optional',{ok:true},3).error,'cleanup_step_out_of_order');});
test('Bug 37: overdue alarm evidence is reported during rehydration',async()=>{const result=await auditAndRehydrateAlarms({schedules:[{alarmName:'pmia-recovery:s',dueAt:5}],now:100});assert.equal(result.overdue.length,1);});
test('Bug 38: a stale owner with a lower incoming generation cannot be displaced',()=>{const current={instanceId:'a',documentId:'d',generation:3,lastSeenAt:0};assert.equal(claimRuntimeInjection(current,{instanceId:'b',documentId:'d2',generation:2},1000,{leaseMs:100}).accepted,false);});
test('Bug 39: discarded page status blocks registration as well as writes',()=>{const result=derivePrerenderGuard({discarded:true});assert.equal(result.allowRegistration,false);assert.equal(result.allowProviderWrite,false);});
test('Bug 40: sequence NACK is metadata-only and preserves buffered envelopes',()=>{const buffer=new ContiguousSequenceBuffer({lastAcceptedSeq:1});buffer.offer({id:'e3',seq:3});const before=buffer.snapshot();const nack=buffer.nack('timeout');assert.equal(nack.expectedSeq,2);assert.deepEqual(buffer.snapshot(),before);});
// Additional bug cycles 41–50.
test('Bug 41: repaired ledger index remains deterministic across repeated repairs',()=>{const entries=[{id:'a',state:'persisted',envelope:{sourceProvider:'p',seq:1}},{id:'a',state:'failed',envelope:{sourceProvider:'p',seq:2}}];const index=new DeliveryLedgerIndex(entries);const first=index.repair(entries);const second=index.repair(first.entries);assert.deepEqual(second.entries.map(entry=>entry.id),first.entries.map(entry=>entry.id));assert.equal(second.audit.ok,true);});
test('Bug 42: receiver credit snapshots expose bounded available capacity',()=>{const credits=new ReceiverCreditHysteresis({recoveryWindowMs:0});credits.update({available:9,capacity:3},{now:1});assert.equal(credits.snapshot().last.available,3);});
test('Bug 43: fairness promotion does not rewrite the selected partition sequence',()=>{const partitions=[{id:'old',oldestAt:0,firstSeq:7,source:'b'},{id:'new',oldestAt:99,firstSeq:8,source:'a'}];const result=scheduleFairBatch(partitions,{now:1201,starvationMs:500});assert.equal(result.selected.firstSeq,7);assert.equal(partitions[0].firstSeq,7);});
test('Bug 44: interrupt token changes when any preserved member changes',()=>{const a=buildInterruptPlan({active:{id:'a',prompt:{memberIds:['1']}},next:{entries:[{id:'2',envelope:{seq:2}},{id:'3',envelope:{seq:3}}]}},10);const b=buildInterruptPlan({active:{id:'a',prompt:{memberIds:['1']}},next:{entries:[{id:'x',envelope:{seq:2}},{id:'3',envelope:{seq:3}}]}},10);assert.notEqual(a.token,b.token);});
test('Bug 45: merging the same protected prompt twice remains idempotent',()=>{let value='manual';const adapter={getComposerText:()=>value,setComposerText:text=>(value=text,true),findComposer:()=>({tagName:'TEXTAREA',getAttribute:()=>'',textContent:value})};const arbiter=createComposerArbiter({adapter});arbiter.writeBatch('protected');value='manual';arbiter.observe();const first=arbiter.resolveConflict('merge');value=first.text;arbiter.observe();const submission=arbiter.submissionTextFor('protected');assert.equal((submission.match(/protected/g)||[]).length,1);});
test('Bug 46: outbox retry intent remains after a failed persistence acknowledgement',async()=>{let fail=false;const outbox=createSenderOutbox({initialEntries:[{envelope:{id:'e',sessionId:'s',seq:1}}],saveState:async()=>{if(fail)throw new Error('x');},now:()=>10});fail=true;assert.equal(await outbox.ackPersisted('e'),false);assert.equal(outbox.size,1);});
test('Bug 47: render scheduler isolates renderer failure and clears pending work',()=>{let frame;const scheduler=createRenderScheduler({frame:fn=>(frame=fn,1),cancelFrame:()=>{}});scheduler.schedule(['a'],()=>{throw new Error('render');});assert.doesNotThrow(()=>frame());assert.deepEqual(scheduler.snapshot().pending,[]);});
test('Bug 48: support-bundle audit fails closed on credential-like nested values',()=>{const bundle=buildSafeSupportBundle({sessionId:'s',performanceBudget:{nested:{value:'Bearer secret-token'}},production:{diagnostics:{privacy:{safe:true}}}},{manifest:{name:'PMIA',version:'0.10.0'}});assert.equal(JSON.stringify(bundle).includes('secret-token'),false);assert.equal(bundle.privacy.safe,true);});
test('Bug 49: release handoff requires exact commit binding and Assist evidence',()=>{const production={diagnostics:{state:'healthy',score:100,privacy:{safe:true},fingerprint:{version:'0.10.0',commit:'abc'}}};const evidence={sourceClean:true,commit:'def',expectedCommit:'abc',automatedOk:true,browserOk:true,assistUiOk:false,cleanupOk:true,noPushMergeTag:true};const result=deriveReleaseHandoff({ledgerCounts:{unresolved:0}},production,evidence);assert.ok(result.failed.includes('commit'));assert.ok(result.failed.includes('assist'));});
test('Bug 50: reliability controls are present with unique IDs and printable markup',()=>{const html=read('index.html');assert.match(html,/id="assistReliabilityState"/);assert.match(html,/id="assistReliabilityGroups"/);const result=auditCommandReachability({registry:COMMAND_REGISTRY,html,dashboardSource:read('dashboard.js'),controllerSource:fs.readFileSync(path.resolve(here,'../shared/runtime-pilot-controller.js'),'utf8')});assert.equal(result.duplicateDomIds.length,0);});